### ISSUE TITLE
Decouple UIKit - to help foster support for android / linux / windows platforms

### ISSUE THREAD

**Issue by johndpope** [craiggrummitt/ActionSwift3#2]
Hi Craig,

I love what you are doing here and Adobe / Google should totally throw some resources behind this.
Given Google are considering using swift as a first class language for Android- having a uikit alternative totally makes sense. Adobe should come to the party and help rebuild actionscript / ui libraries in swift. 
This is an amazing job you've started. I built an objective-c to swift converter -> objc2swift.io I open sourced it on github - https://github.com/BellGeorge/objc2swift.io/ 

Porting flash over to swift is something that I'm looking to embark on shortly. 
There's so many syntactical similarities. 

I know Facebook rebuilt their uitableview to speed up things. AsyncDisplay.
I'd need to take another look - but removing UIKit would be a milestone.....do you agree? 
Can core image be used on android? 

Can you envisage  this project working on other platforms ? 
<img width="1001" alt="screen shot 2016-04-24 at 7 51 50 pm" src="https://cloud.githubusercontent.com/assets/289994/14771343/0dfe342c-0a56-11e6-975e-94181219bcf8.png">

**Comment by craiggrummitt** [comment]
Hi John, thanks for all of your comments. Love your idea to decouple it from iOS frameworks(it's actually coupled with UIKit **and** SpriteKit - mainly SpriteKit). Unless I'm mistaken, the open source Swift code wouldn't give us access to underlying graphics capabilities however, i.e. you would need to still incorporate underlying frameworks to access the display. But I love the idea of this being cross platform, and think there could be a way.

I'm thinking all the files that do couple it could be swapped out, in fact some of this work is already done - for example, the _com/actionswift/display/internal_ group contains several nodes that sublass varying iOS SKNodes. These files that do couple it could then be swapped out where necessary. For example these SKNodes subclasses could be swapped out for Android CCNodes, with appropriate methods/properties to bridge it to the underlying platform. 

I guess depending on how the project was opened would then determine which platform specific swift files get included. For example, if you open the xcodeproj project file you would obviously want the iOS platform(If we wanted to include OSX, we could include this as another target) files. If you open it as an Android project, you would get any Android files. 

Then, you would have consistent code - ActionSwift - not just across platforms which Swift will provide(supposedly, if Android does do this), but across platform specific frameworks. And as you say, alternative custom views, controls etc could be built up, just like Facebook have built their own table view. And if Adobe or Google got on board, sky's the limit...

**Comment by johndpope** [comment]
fyi https://swiftforwindows.codeplex.com/discussions

**Comment by johndpope** [comment]
hey @craiggrummitt - fyi - I hacked this tree walker for proto / java files in swift
https://github.com/johndpope/Antlr-Swift-runtime

looking to convert some java to swift converter together. 
The ecma gramma file has some troubles. Need to find time to debug. 
https://github.com/johndpope/ANTLR-Swift-Target/tree/master/gen/grammars-v4/ecmascript

**Comment by johndpope** [comment]
hey @craiggrummitt -   fyi - https://github.com/SwiftGFX/SwiftBGFX

**Comment by johndpope** [comment]
https://github.com/s1ddok/Fiber2D

**Comment by johndpope** [comment]
fyi - https://github.com/TomasLinhart/SwiftGtk

**Comment by johndpope** [comment]
closing due to spring cleaning.
