### ISSUE TITLE
feature - actionscript to ActionSwift3 converter

### ISSUE THREAD

**Issue by johndpope** [craiggrummitt/ActionSwift3#4]
https://github.com/yahoojapan/objc2swift
This may warrant an entirely new project - but consider

the ecmascript standard is a known antlr format - 
hypothetically -we could rejig the antlr grammar file from ecma to swift then rebuild this project here  
https://github.com/yahoojapan/objc2swift

I have a ticket open for the code generation 
https://github.com/yahoojapan/objc2swift/issues/22

I can imagine a webpage like this - where people could throw some actionscript class /or python for that matter - and it would spit out the corresponding  swift class - easy - peasy. 

![demo](https://cloud.githubusercontent.com/assets/289994/14773673/1956e7fe-0a7b-11e6-81fc-4e32a252adc8.gif)

I actually own the property http://objc2swift.io  which I open sourced some time ago.

**Comment by craiggrummitt** [comment]
Wow, very interesting idea. Keep me in the loop.
A difficulty I imagine is how does a non-strict language get auto-converted to a strict language? I guess you would have to enforce strictness in the AS code.

**Comment by johndpope** [comment]
fyi https://github.com/janyou/Antlr-Swift-Runtime
https://github.com/janyou/ANTLR-Swift-Target

It's possible to download these repo's and switch in the ecma script grammar file
https://raw.githubusercontent.com/antlr/grammars-v4/master/ecmascript/ECMAScript.g4
this will produce swift parsers.

**Comment by johndpope** [comment]
updated walker code 
https://github.com/johndpope/Antlr-Swift-runtime
