### ISSUE TITLE
fyi - sparrow -  objective-c port  / game engine for actionscript

### ISSUE THREAD

**Issue by johndpope** [craiggrummitt/ActionSwift3#6]
came across this looking at as3lang.org http://gamua.com/starling/
https://twitter.com/as3lang

https://github.com/Gamua/Sparrow-Framework/tree/master/sparrow/src/Classes

**Comment by craiggrummitt** [comment]
Very interesting, I am very familiar with Starling(in fact I had a look at Starling source as I worked on ActionSwift), but wasn't aware of Sparrow.
